<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="PingException.xml" source-language="en-US" target-language="ru-RU">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5f431952bc2bd00792eaf22d97cfc26ac37339481.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">f431952bc2bd00792eaf22d97cfc26ac37339481</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Net.NetworkInformation.PingException">
          <source>The exception that is thrown when a <ph id="ph1">&lt;see cref="Overload:System.Net.NetworkInformation.Ping.Send" /&gt;</ph> or <ph id="ph2">&lt;see cref="Overload:System.Net.NetworkInformation.Ping.SendAsync" /&gt;</ph> method calls a method that throws an exception.</source>
          <target state="translated">Исключение возникает, когда метод <ph id="ph1">&lt;see cref="Overload:System.Net.NetworkInformation.Ping.Send" /&gt;</ph> или <ph id="ph2">&lt;see cref="Overload:System.Net.NetworkInformation.Ping.SendAsync" /&gt;</ph> вызывают метод, приводящий к исключению.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Net.NetworkInformation.PingException">
          <source>The <ph id="ph1">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> class throws this exception to indicate that while sending an Internet Control Message Protocol (ICMP) Echo request, a method called by the <ph id="ph2">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> class threw an unhandled exception.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> Класс этого исключения для указания, что при отправке запроса управления сообщений протокола ICMP (Internet), метод вызывается методом <ph id="ph2">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> класса создала необработанное исключение.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Net.NetworkInformation.PingException">
          <source>Applications should check the inner exception of a <ph id="ph1">&lt;xref:System.Net.NetworkInformation.PingException&gt;</ph> object to identify the problem.</source>
          <target state="translated">Приложения должны проверять внутреннее исключение <ph id="ph1">&lt;xref:System.Net.NetworkInformation.PingException&gt;</ph> объекта, чтобы определить проблему.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Net.NetworkInformation.PingException">
          <source>The <ph id="ph1">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> class does not throw this exception if the ICMP Echo request fails because of network, ICMP, or destination errors.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> Класса не вызывают это исключение, если запрос проверки связи ICMP завершается неудачей из-за ошибок сети, ICMP или назначения.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Net.NetworkInformation.PingException">
          <source>For such errors, the <ph id="ph1">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> class returns a <ph id="ph2">&lt;xref:System.Net.NetworkInformation.PingReply&gt;</ph> object with the relevant <ph id="ph3">&lt;xref:System.Net.NetworkInformation.IPStatus&gt;</ph> value set in the <ph id="ph4">&lt;xref:System.Net.NetworkInformation.PingReply.Status%2A&gt;</ph> property.</source>
          <target state="translated">Для таких ошибок <ph id="ph1">&lt;xref:System.Net.NetworkInformation.Ping&gt;</ph> возвращает <ph id="ph2">&lt;xref:System.Net.NetworkInformation.PingReply&gt;</ph> объект с соответствующего <ph id="ph3">&lt;xref:System.Net.NetworkInformation.IPStatus&gt;</ph> в значение <ph id="ph4">&lt;xref:System.Net.NetworkInformation.PingReply.Status%2A&gt;</ph> свойства.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="T:System.Net.NetworkInformation.PingException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph> class.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String)">
          <source>A <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph> that describes the error.</source>
          <target state="translated">Строка <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph>, описывающая ошибку.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph> class using the specified message.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph>, используя указанное сообщение.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String)">
          <source>This constructor initializes the <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> property with the text in the <ph id="ph2">`message`</ph> parameter.</source>
          <target state="translated">Этот конструктор инициализирует <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> свойство с текстом в <ph id="ph2">`message`</ph> параметра.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property is set to <ph id="ph2">`null`</ph>.</source>
          <target state="translated">Свойству <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> задано значение <ph id="ph2">`null`</ph>.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">Объект, содержащий сериализованные данные объекта.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>A <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> that specifies the contextual information about the source or destination for this serialization.</source>
          <target state="translated">Объект <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph>, содержащий контекстные сведения о начальном или конечном объекте сериализации.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph> с сериализованными данными.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called during deserialization to reconstitute a previously serialized <ph id="ph1">&lt;xref:System.Net.NetworkInformation.PingException&gt;</ph> object.</source>
          <target state="translated">Данный конструктор вызывается в процессе десериализации для воссоздания ранее сериализованного <ph id="ph1">&lt;xref:System.Net.NetworkInformation.PingException&gt;</ph> объекта.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)">
          <source>A <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph> that describes the error.</source>
          <target state="translated">Строка <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph>, описывающая ошибку.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)">
          <source>The exception that causes the current exception.</source>
          <target state="translated">Исключение, которое вызывает текущее исключение.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph> class using the specified message and inner exception.</source>
          <target state="translated">Инициализирует новый экземпляр класса <ph id="ph1">&lt;see cref="T:System.Net.NetworkInformation.PingException" /&gt;</ph>, используя указанное сообщение и внутреннее исключение.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Net.NetworkInformation.PingException.#ctor(System.String,System.Exception)">
          <source>This constructor initializes the <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> property with the text in the <ph id="ph2">`message`</ph> parameter, and the <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property with the <ph id="ph4">`innerException`</ph> parameter.</source>
          <target state="translated">Этот конструктор инициализирует <ph id="ph1">&lt;xref:System.Exception.Message%2A&gt;</ph> свойство с текстом в <ph id="ph2">`message`</ph> параметра и <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> свойство с <ph id="ph4">`innerException`</ph> параметра.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>