<Type Name="XamlInternalException" FullName="System.Xaml.XamlInternalException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="0729fa9645baf6a20d37770d139f103712c6612f" />
    <Meta Name="ms.sourcegitcommit" Value="d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="ru-RU" />
    <Meta Name="ms.lasthandoff" Value="04/03/2018" />
    <Meta Name="ms.locfileid" Value="30685968" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class XamlInternalException : System.Xaml.XamlException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit XamlInternalException extends System.Xaml.XamlException" />
  <TypeSignature Language="DocId" Value="T:System.Xaml.XamlInternalException" />
  <TypeSignature Language="VB.NET" Value="Public Class XamlInternalException&#xA;Inherits XamlException" />
  <TypeSignature Language="C++ CLI" Value="public ref class XamlInternalException : System::Xaml::XamlException" />
  <AssemblyInfo>
    <AssemblyName>System.Xaml</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Xaml.XamlException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="a3440-101">Исключение, которое создается в случаях внутренних несоответствий, возникающих во время чтения и записи XAML.</span>
      <span class="sxs-lookup">
        <span data-stu-id="a3440-101">The exception that is thrown for internal inconsistencies that occur during XAML reading and XAML writing.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="a3440-102">Это исключение обычно вызывается только в том случае, когда некоторые аспекты средства чтения XAML или системы средство записи XAML была расширена в коде, и несоответствия или проблемы реализации возникла, переданные системного кода служб XAML .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="a3440-102">This exception is usually thrown only when some aspect of the XAML reader or XAML writer system was extended by your code, and inconsistencies or implementation problems occurred that were passed on to the .NET Framework XAML Services system code.</span></span> <span data-ttu-id="a3440-103">Исключения, которые может быть создано сторонних производителей, например, синтаксический анализ кода XAML и обнаружения ошибок в XAML-ФАЙЛЕ, не должны вызывать <xref:System.Xaml.XamlInternalException>и вместо этого должны вызывать другие исключения например <xref:System.Xaml.XamlParseException> или <xref:System.Xaml.XamlObjectWriterException>.</span><span class="sxs-lookup"><span data-stu-id="a3440-103">Exceptions that might originate from third parties, such as parsing XAML and encountering errors in the XAML, should not throw <xref:System.Xaml.XamlInternalException>, and should instead throw other exceptions such as <xref:System.Xaml.XamlParseException> or <xref:System.Xaml.XamlObjectWriterException>.</span></span>  
  
 <span data-ttu-id="a3440-104">Если вы пишете код, который расширяет возможности служб XAML .NET Framework, в частности, при написании кода для средства чтения XAML или реализацию модуля записи XAML, необходимо поддерживать это различие между <xref:System.Xaml.XamlInternalException> и другие исключения, связанные с XAML.</span><span class="sxs-lookup"><span data-stu-id="a3440-104">If you are writing code that extends .NET Framework XAML Services, in particular, if you are writing code for a XAML reader or XAML writer implementation, you should maintain this distinction between <xref:System.Xaml.XamlInternalException> and the other XAML-related exceptions.</span></span> <span data-ttu-id="a3440-105">Код создается только <xref:System.Xaml.XamlInternalException> в случаях, когда это нарушает некоторые принцип или реализации шаблона разработки, вызываемых код определяет дальнейшее расширение класса.</span><span class="sxs-lookup"><span data-stu-id="a3440-105">Your code should only throw <xref:System.Xaml.XamlInternalException> in cases where further extension of your class violates some design principle or implementation pattern that your callable code defines.</span></span> <span data-ttu-id="a3440-106">Код должен вызывать другие исключения, связанные с XAML для исключения случаев, когда средства чтения или записи реализации XAML используется без расширения и используется для загрузки XAML сторонних разработчиков, стороннего контекста схемы XAML и т. д.</span><span class="sxs-lookup"><span data-stu-id="a3440-106">Your code should throw other XAML-specific exceptions for exception cases where your XAML reader or XAML writer implementation is used without extension and is used to load third-party XAML, third-party XAML schema context, and so on.</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="T:System.Xaml.XamlParseException" />
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="a3440-107">Инициализирует новый экземпляр класса <see cref="T:System.Xaml.XamlInternalException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-107">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlInternalException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlInternalException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="a3440-108">Инициализирует новый экземпляр класса <see cref="T:System.Xaml.XamlInternalException" /> с системным сообщением, содержащим описание ошибки.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-108">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with a system-supplied message that describes the error.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlInternalException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlInternalException(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="a3440-109">Сообщение с описанием исключения.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-109">The message that describes the exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="a3440-110">Инициализирует новый экземпляр класса <see cref="T:System.Xaml.XamlInternalException" /> с использованием заданного сообщения, содержащего описание ошибки.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-110">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with a specified message that describes the error.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected XamlInternalException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; XamlInternalException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="a3440-111">Объект, содержащий сериализованные данные объекта.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-111">The object that holds the serialized object data.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="a3440-112">Контекстные сведения об источнике или назначении.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-112">The contextual information about the source or destination.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="a3440-113">Инициализирует новый экземпляр класса <see cref="T:System.Xaml.XamlInternalException" /> с сериализованными данными.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-113">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with serialized data.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public XamlInternalException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; XamlInternalException(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Xaml</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="a3440-114">Сообщение с описанием исключения.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-114">The message that describes the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="a3440-115">Исключение, которое является причиной текущего исключения.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-115">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="a3440-116">Если значение параметра <c>innerException</c> не равно <see langword="null" />, текущее исключение возникает в блоке <see langword="catch" />, обрабатывающем внутреннее исключение.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-116">If the <c>innerException</c> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="a3440-117">Инициализирует новый экземпляр класса <see cref="T:System.Xaml.XamlInternalException" /> указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение.</span>
          <span class="sxs-lookup">
            <span data-stu-id="a3440-117">Initializes a new instance of the <see cref="T:System.Xaml.XamlInternalException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>